### ISSUE TITLE
Testnet deployments

### ISSUE THREAD

**Issue by WyseNynja** [1inch/1inchProtocol#15]
I have some contracts almost ready for deployment to mainnet, but want to run some tests on a public test network.

Is 1split deployed to ropsten or another test network?

**Comment by bhargav55** [comment]
How to test token swaps by integrating with 1inch smart contracts ? Do you have 1inch.exchange deployed in tesnets ?

**Comment by gtech** [comment]
I'm bumping this. Gas prices are insane, so API and smart contract support on testnets would be awesome.

**Comment by danipisca07** [comment]
Agreed. Totally need this

**Comment by harshoffice** [comment]
Anyone deployed 1inchon testnet or have a testnet contract address. pls share thanks

**Comment by tperalta82** [comment]
Bumping this

**Comment by k06a** [comment]
You can perform `eth_call` with the transaction calldata to simulate execution and get return values.

**Comment by peetzweg** [comment]
1inch on any testnet would be sooooo helpful.

**Comment by apostgit** [comment]
Yes please. This would be really useful!

**Comment by raphael-mazet** [comment]
An alternative is to use 1Inch on Polygon. Much lower gas fees

**Comment by ghost** [comment]
Would really like to see 1inch support erc testnet. Else there is no reason to move from uniswap.

**Comment by alexanderem49** [comment]
Bumping it. Need testnet deployment

**Comment by chitter99** [comment]
Bumping this :)

**Comment by BasilF696** [comment]
Bumping!

**Comment by krboktv** [comment]
There is no testnet or local network for 1inchProtocol contract because we don’t have all liquidity sources on testnet.

Anyway, you can use ganache fork to emulate real mainnet calls

https://github.com/trufflesuite/ganache-cli

How to use:

Install ganache-cli

Run next command to setup a mainnet fork

ganache-cli --fork node-url -p 9545 --gasLimit 0xfffffffffff

Next you can connect to Web3 Provider on remix.ethereum.org with 9545 port (you can do that also via code)

And emulate execution for all data

**Comment by EgusCpp** [comment]
Hello @krboktv , could you please clarify, if I install ganache, then what address should I use instead https://tx-gateway.1inch.io ? Should I deploy 1inch programs there? And what about tokens? They are seems to be not existing by default. In other words, if 1 inch still not exists on chains like Goerli, it would be great to add details to Quickstart, to let people able to use it without spending lots of money on real transactions just for software testing.

**Comment by danipisca07** [comment]
> Hello @krboktv , could you please clarify, if I install ganache, then what address should I use instead https://tx-gateway.1inch.io ? Should I deploy 1inch programs there? And what about tokens? They are seems to be not existing by default. In other words, if 1 inch still not exists on chains like Goerli, it would be great to add details to Quickstart, to let people able to use it without spending lots of money on real transactions just for software testing.

With ganache you can make a fork of the mainnet starting from the current block. Thank way you replicate the current state of the blockchain, meaning all the contracts deployed there will be available also on your local fork. When ganache starts it tells you the address to use to connect, then you can make transactions as if you are on the official mainnet.

**Comment by hasnain-shahzad** [comment]
Hi @danipisca07 @krboktv , i have tried calling onsplitsudit methods in sequence mentioned in this repo documentation using my ganache fork and web3. getExpectedReturn() method works fine , it returns expectedAmount and distribution parts array. When i call the swap() method next with specified arguments , it does'nt return any error but it dont give any returnAmount in result as mentioned in docs . Kindly elaborate if there is no error and swap method is executed correctly without any result i.e an empty object , does it means that swapping has been done , as ganache just emulates the mainnet transactions. Any help will be highly appreciated.

**Comment by SrishtiLodhi** [comment]
I have been also facing the same issue

**Comment by mikepadial** [comment]
Truffle/Ganache is being sunset, is their another way I cant test or fork the mainnet?

**Comment by 0xpaperhead** [comment]
: )
